# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
     id-token: write
     contents: read
     checks: write

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      id: setup-dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Select .NET 10 SDK
      run: dotnet new globaljson --sdk-version "${{ steps.setup-dotnet.outputs.dotnet-version }}" --roll-forward latestPatch --force
    - name: Show .NET SDK
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFilePrefix=test-results"
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results*.trx"
        reporter: dotnet-trx
        fail-on-error: true
